services:
  db:
    image: pgvector/pgvector:pg17
    container_name: postgres_container
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # This checks if Postgres is actually ready to accept connections
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./app
    container_name: fastapi_app
    depends_on:
      db:
        condition: service_healthy # This is the fix for "Connection Refused"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${POSTGRES_URL}
      ICD11_API_URL: http://icd11:8080
      ICD11_RELEASE: 2026-01
      ICD11_LANGUAGE: es
    volumes:
      - ./app:/code
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  icd11:
    image: whoicd/icd-api
    environment:
      acceptLicense: "true"
      saveAnalytics: "false"
      include: 2026-01_es
    ports:
      - "8081:8080"

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - app

volumes:
  postgres_data:
